# Esto configura:

#     Un servicio web llamado tareas-backend
#     Usa Docker como entorno.
#     El comando buildCommand permite construir el front
#     El comando de inicio ejecuta Apache con el comando apache2-foreground.
#     El archivo Dockerfile se encuentra dentro de la carpeta backend

services:

  # tipo de servicio
  - type: web

    # Nombre del servicio
    name: tareasPHP

    # Entorno de ejecucion
    env: docker

    # Ruta del archivo Dockerfile
    dockerfilePath: ./backend/Dockerfile

    # Directorio de contexto para la construcción
    dockerContextDir: ./tutoriales/php/tareasPHP

    # Comando para construir el frontend
    buildCommand: "npm install && npm run build"

    # Comando para iniciasr los servicios definidos en docker-compose.yml
    startCommand: docker-compose up
  
